//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneySQContext
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ZZ_APPLICATION
    {
        [Key, Column(Order = 0)]
        public string company_code { get; set; }
        [Key, Column(Order = 1)]
        public string application_no { get; set; }
        public string application_no_front { get; set; }
        public string application_category { get; set; }
        public Nullable<System.DateTime> date_of_application { get; set; }
        public string status_of_application { get; set; }
        public string data_created_method { get; set; }
        public string type_of_applicant { get; set; }
        public string idno_of_applicant { get; set; }
        public string name_of_applicant { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string sex_code { get; set; }
        public Nullable<System.DateTime> issue_date { get; set; }
        public string issue_category { get; set; }
        public string name_of_father { get; set; }
        public string name_of_mother { get; set; }
        public string name_of_spouse { get; set; }
        public string birthplace { get; set; }
        public string military_category { get; set; }
        public string identity_card_no { get; set; }
        public string nhi_ic_card_no { get; set; }
        public string issue_city { get; set; }
        public Nullable<System.DateTime> setup_date { get; set; }
        public string currency_type { get; set; }
        public Nullable<decimal> amt_for_applying { get; set; }
        public Nullable<short> period_for_applying { get; set; }
        public string programid_for_applying { get; set; }
        public Nullable<short> empolyeeno_of_service_staff { get; set; }
        public Nullable<short> empolyeeno_for_performance { get; set; }
        public string divisioncode_for_performance { get; set; }
        public string permanent_address { get; set; }
        public string permanent_address_zipcode { get; set; }
        public string permanent_address_city { get; set; }
        public string permanent_address_town { get; set; }
        public string permanent_address_street { get; set; }
        public string permanent_address_li { get; set; }
        public string permanent_address_lin { get; set; }
        public string permanent_address_section { get; set; }
        public string permanent_address_lane { get; set; }
        public string permanent_address_alley { get; set; }
        public string permanent_address_no { get; set; }
        public string permanent_address_floor { get; set; }
        public string permanent_address_room { get; set; }
        public string mailing_address { get; set; }
        public string mailing_address_zipcode { get; set; }
        public string mailing_address_city { get; set; }
        public string mailing_address_town { get; set; }
        public string mailing_address_street { get; set; }
        public string mailing_addresss_li { get; set; }
        public string mailing_addresss_lin { get; set; }
        public string mailing_address_section { get; set; }
        public string mailing_address_lane { get; set; }
        public string mailing_address_alley { get; set; }
        public string mailing_address_no { get; set; }
        public string mailing_address_floor { get; set; }
        public string mailing_address_room { get; set; }
        public string email { get; set; }
        public string cell_phone { get; set; }
        public string job_title { get; set; }
        public string education_level_cd { get; set; }
        public string living_condition_cd { get; set; }
        public string monthly_income_code { get; set; }
        public string marital_status_cd { get; set; }
        public string digital_certificate_status { get; set; }
        public string consent_letter_sign_status { get; set; }
        public string applicant_bankcode { get; set; }
        public string applicant_bankbranch_code { get; set; }
        public string applicant_bank_account { get; set; }
        public Nullable<decimal> suggested_interest_rate { get; set; }
        public Nullable<decimal> suggested_amt { get; set; }
        public string suggested_contract_type { get; set; }
        public string suggested_opinion { get; set; }
        public Nullable<decimal> approved_interest_rate { get; set; }
        public Nullable<decimal> approved_amt { get; set; }
        public string approved_contract_type { get; set; }
        public Nullable<System.DateTime> datetime_of_acceptence { get; set; }
        public Nullable<short> case_officer_employeeno { get; set; }
        public string opr_id { get; set; }
        public string opr_name { get; set; }
        public System.DateTime opr_date { get; set; }
        public string opr_ip_address { get; set; }
        public string opr_gps_address { get; set; }
        public Nullable<bool> enable_push { get; set; }
    }
}
