//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class comUser
    {
        public string user_id { get; set; }
        public string country { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string nickname { get; set; }
        public string directline { get; set; }
        public string password { get; set; }
        public string dept { get; set; }
        public string role { get; set; }
        public string email { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<bool> show_report { get; set; }
        public Nullable<bool> access_report { get; set; }
        public Nullable<bool> access_print { get; set; }
        public Nullable<bool> limited_user { get; set; }
        public Nullable<bool> advanced_user { get; set; }
        public string last_upd_user { get; set; }
        public Nullable<System.DateTime> last_upd_date { get; set; }
    }
}
