//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class followup_issues
    {
        public decimal pk { get; set; }
        public string loan_id { get; set; }
        public Nullable<int> status_id { get; set; }
        public string cs_officer { get; set; }
        public string cr_officer { get; set; }
        public Nullable<System.DateTime> sign_date { get; set; }
        public string cusName { get; set; }
        public string tel { get; set; }
        public Nullable<System.DateTime> telCheckDate { get; set; }
        public string telCheckTime { get; set; }
        public string priority { get; set; }
        public Nullable<System.DateTime> received_date { get; set; }
        public Nullable<System.DateTime> completed_date { get; set; }
        public string byCR { get; set; }
        public string byCS { get; set; }
        public string byLR { get; set; }
    }
}
