//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class loanApplication_exCustomer_raw
    {
        public int pk { get; set; }
        public string refno { get; set; }
        public string loan_amt { get; set; }
        public string interest { get; set; }
        public string tel { get; set; }
        public string address { get; set; }
        public string priority { get; set; }
        public string borrower { get; set; }
        public string id_num { get; set; }
        public Nullable<System.DateTime> redemption_date { get; set; }
        public string redemption_reason { get; set; }
    }
}
