//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class loanApplication
    {
        public string order_nbr { get; set; }
        public string order_nbr_old { get; set; }
        public string country { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> pre_approved_id { get; set; }
        public Nullable<bool> urgent { get; set; }
        public Nullable<bool> isExp { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public string order_time { get; set; }
        public Nullable<System.DateTime> not_consider_date { get; set; }
        public Nullable<System.DateTime> apply_date { get; set; }
        public Nullable<System.DateTime> replyCus_date { get; set; }
        public string user_id { get; set; }
        public string rej_reason { get; set; }
        public string applicant { get; set; }
        public string proprietor { get; set; }
        public string phone { get; set; }
        public string income_proff { get; set; }
        public string income_proff_amt { get; set; }
        public string loan_type { get; set; }
        public string mortgage { get; set; }
        public string loan_amt { get; set; }
        public string req_loanRevDate { get; set; }
        public string loan_purpose { get; set; }
        public string remarks { get; set; }
        public string checker1 { get; set; }
        public string checker2 { get; set; }
        public string approver { get; set; }
        public string pass_approved { get; set; }
        public string exclusiveFlag { get; set; }
        public Nullable<bool> exclude { get; set; }
        public Nullable<bool> isSMS { get; set; }
        public Nullable<bool> isSMS_sent { get; set; }
        public Nullable<bool> noSMS { get; set; }
        public Nullable<bool> is_followup { get; set; }
        public Nullable<int> smsCount { get; set; }
        public Nullable<System.DateTime> lst_smsDate { get; set; }
        public Nullable<System.DateTime> lst_replyDate { get; set; }
        public Nullable<System.DateTime> threeMonSMSDate { get; set; }
        public string smsMobile { get; set; }
        public string smsAmt1 { get; set; }
        public string smsAmt2 { get; set; }
        public string smsAmt3 { get; set; }
        public string smsAmt4 { get; set; }
        public string smsAmt5 { get; set; }
        public string smsReplier { get; set; }
        public string credit_notes { get; set; }
        public Nullable<bool> re_approval { get; set; }
        public string intention_level { get; set; }
        public Nullable<bool> privacy { get; set; }
        public string editing_by { get; set; }
        public string refno { get; set; }
        public Nullable<System.DateTime> sign_date { get; set; }
        public string sign_time { get; set; }
        public Nullable<System.DateTime> start_rent_date { get; set; }
        public string loan_term { get; set; }
        public string loan_penalty_term { get; set; }
        public string payment_method { get; set; }
        public string interest_flag { get; set; }
        public string interest { get; set; }
        public string iOnly_period { get; set; }
        public string accName { get; set; }
        public string accNum { get; set; }
        public string accBank { get; set; }
        public string refinance_amt { get; set; }
        public string setup_amt { get; set; }
        public string first_install_method { get; set; }
        public string mon_install_amt { get; set; }
        public string pay_day { get; set; }
        public Nullable<System.DateTime> first_install_date { get; set; }
        public Nullable<System.DateTime> property_view_date { get; set; }
        public string property_view_time { get; set; }
        public string contractPropertyNum { get; set; }
        public string contractType { get; set; }
        public string contractConpenAmt { get; set; }
        public string contractConpenName { get; set; }
        public string contractBorrowerOut { get; set; }
        public string contractAdminFee { get; set; }
        public string payBack_accName { get; set; }
        public string payBack_accNum { get; set; }
        public string payBack_accBank { get; set; }
        public Nullable<System.DateTime> completed_date { get; set; }
        public Nullable<bool> is_contractTaxFee { get; set; }
        public Nullable<bool> is_contractAdminFee { get; set; }
        public Nullable<bool> is_contractClaimFee { get; set; }
        public Nullable<bool> is_payWithTax { get; set; }
        public string last_upd_user { get; set; }
        public Nullable<System.DateTime> last_upd_date { get; set; }
        public Nullable<bool> IsRefinance { get; set; }
        public string accBranch { get; set; }
        public string payBack_accBranch { get; set; }
        public Nullable<bool> is_from_callcenter { get; set; }
        public string callcenter_user_id { get; set; }
        public string pass_pendingForApproval { get; set; }
        public Nullable<System.DateTime> legal_attest_letter_last_pay_date { get; set; }
        public string legal_attest_letter_amt_type { get; set; }
        public string legal_attest_letter_breach_clause { get; set; }
        public string legal_attest_letter_company_type { get; set; }
        public Nullable<int> pre_status_id { get; set; }
        public string all_status_id { get; set; }
        public Nullable<bool> agent { get; set; }
    }
}
