//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class loanApplication_contractProperty
    {
        public int pk { get; set; }
        public string order_nbr { get; set; }
        public string country { get; set; }
        public string owner { get; set; }
        public string propertyType { get; set; }
        public string address { get; set; }
        public string contractPropertyNum { get; set; }
        public string contractPortion1 { get; set; }
        public string contractPortion2 { get; set; }
        public string property_area { get; set; }
        public string property_remarks { get; set; }
        public string contractPropertyCity { get; set; }
        public string contractPropertyRegion { get; set; }
        public string contractPropertySection { get; set; }
        public string contractPropertySectionNum { get; set; }
        public string contractPropertyOwner { get; set; }
    }
}
