//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class loanApplication_exCustomer
    {
        public int order_nbr { get; set; }
        public int status { get; set; }
        public string refno { get; set; }
        public Nullable<System.DateTime> redem_date { get; set; }
        public string redem_reason { get; set; }
        public string loan_amt { get; set; }
        public string interest { get; set; }
        public string replier { get; set; }
        public Nullable<System.DateTime> reply_date { get; set; }
        public string intention_level { get; set; }
        public string remarks { get; set; }
    }
}
