//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class loanApplicationSMSlog
    {
        public decimal sms_pk { get; set; }
        public string order_nbr { get; set; }
        public string mobile { get; set; }
        public string user_id { get; set; }
        public string sms_content { get; set; }
        public Nullable<System.DateTime> smsDate { get; set; }
    }
}
