//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class refinanceApplication
    {
        public decimal refinance_pk { get; set; }
        public string loan_no { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> callin_date { get; set; }
        public string callin_time { get; set; }
        public Nullable<int> version { get; set; }
        public Nullable<bool> exclude { get; set; }
        public string contact_person { get; set; }
        public string phone { get; set; }
        public string contract_type { get; set; }
        public string loan_type { get; set; }
        public string request_amt { get; set; }
        public string require_redem { get; set; }
        public string require_redem_item { get; set; }
        public string net_amt { get; set; }
        public string handle_by_1 { get; set; }
        public string purpose_type { get; set; }
        public string purpose { get; set; }
        public string os_item { get; set; }
        public string os_item_amt { get; set; }
        public string other_properties { get; set; }
        public Nullable<bool> print_redem_report { get; set; }
        public string reten_repaid_exp_flag { get; set; }
        public string reten_repaid_exp { get; set; }
        public string repaid_exp_flag { get; set; }
        public string repaid_exp { get; set; }
        public string prepaid_exp_flag { get; set; }
        public string prepaid_exp { get; set; }
        public string credit_limit_flag { get; set; }
        public string credit_limit { get; set; }
        public string credit_limit_source { get; set; }
        public string tu_flag { get; set; }
        public string tu_amt { get; set; }
        public string add_flag { get; set; }
        public string property_view_flag { get; set; }
        public string property_view { get; set; }
        public string trans_to { get; set; }
        public string trans_source { get; set; }
        public string trans_loanType { get; set; }
        public string trans_loan_amt { get; set; }
        public string trans_terms { get; set; }
        public string trans_interest { get; set; }
        public string trans_pmt { get; set; }
        public Nullable<bool> trans_IsPrincipal { get; set; }
        public Nullable<bool> trans_IsInterest { get; set; }
        public string trans_bargainRate { get; set; }
        public string trans_reason { get; set; }
        public string trans_reject_reason { get; set; }
        public Nullable<bool> remarks_checked { get; set; }
        public string remarks_refinance { get; set; }
        public Nullable<bool> hight_remarks { get; set; }
        public Nullable<bool> pass_to_cc { get; set; }
        public Nullable<bool> isNewAction { get; set; }
        public string hasLegalFee { get; set; }
        public string interest_type { get; set; }
        public string refinance_amt { get; set; }
        public string redeem { get; set; }
        public string redeem_item { get; set; }
        public string interest_flag { get; set; }
        public string interest { get; set; }
        public string valuation_amt { get; set; }
        public Nullable<System.DateTime> valuation_date { get; set; }
        public string valuation_staff { get; set; }
        public string new_credit_limit_flag { get; set; }
        public string new_credit_limit_amt { get; set; }
        public string remarks { get; set; }
        public string credit_notes { get; set; }
        public string approved_by { get; set; }
        public string tu_outstanding { get; set; }
        public string credit_ratio_tu { get; set; }
        public string credit_ratio_notu { get; set; }
        public string risk_level { get; set; }
        public string refinance_details { get; set; }
        public string refinance_history { get; set; }
        public Nullable<bool> checkByCC { get; set; }
        public string approval_status { get; set; }
        public Nullable<bool> revise_data { get; set; }
        public Nullable<bool> isApproved { get; set; }
        public Nullable<bool> isReturn { get; set; }
        public Nullable<bool> is_redemLetter { get; set; }
        public Nullable<System.DateTime> redem_date { get; set; }
        public string last_upd_user { get; set; }
        public Nullable<System.DateTime> last_upd_date { get; set; }
    }
}
