//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class refinanceItem
    {
        public decimal refinance_pk { get; set; }
        public string loan_no { get; set; }
        public Nullable<System.DateTime> sign_date { get; set; }
        public string sign_time { get; set; }
        public string loan_term { get; set; }
        public string handled_by { get; set; }
        public Nullable<bool> stop_autocash { get; set; }
        public Nullable<bool> autocash_form { get; set; }
        public string payment_method { get; set; }
        public string interest_flag { get; set; }
        public string interest { get; set; }
        public string refinance_amt { get; set; }
        public string first_install_method { get; set; }
        public string mon_install_amt { get; set; }
        public string pay_day { get; set; }
        public Nullable<System.DateTime> first_install_date { get; set; }
        public string first_install_type { get; set; }
        public string first_install_by { get; set; }
        public string sec_install_by { get; set; }
        public Nullable<System.DateTime> property_view_date { get; set; }
        public string property_view_time { get; set; }
        public Nullable<bool> property_view_approve { get; set; }
        public string first_mort_outstanding_flag { get; set; }
        public string first_mort_outstanding_amt { get; set; }
        public Nullable<System.DateTime> first_mort_outstanding_date { get; set; }
        public string first_mort_outstanding_time { get; set; }
        public string credit_card_outstanding_flag { get; set; }
        public string credit_card_outstanding_amt { get; set; }
        public Nullable<System.DateTime> credit_card_outstanding_date { get; set; }
        public string credit_card_outstanding_time { get; set; }
        public string management_fee_flag { get; set; }
        public string management_fee_amt { get; set; }
        public Nullable<System.DateTime> management_fee_date { get; set; }
        public string management_fee_time { get; set; }
        public string rates_flag { get; set; }
        public string rates_amt { get; set; }
        public Nullable<System.DateTime> rates_date { get; set; }
        public string rates_time { get; set; }
        public string declare_item1_flag { get; set; }
        public string declare_item1 { get; set; }
        public string declare_item1_amt { get; set; }
        public string declare_item2_flag { get; set; }
        public string declare_item2 { get; set; }
        public string declare_item2_amt { get; set; }
        public string legal_remarks { get; set; }
        public string legal_remarks_read_by { get; set; }
        public Nullable<bool> legal_remarks_highlight { get; set; }
        public Nullable<bool> legal_checked { get; set; }
        public Nullable<bool> is_authLetter { get; set; }
        public Nullable<bool> is_dischargeCancel { get; set; }
    }
}
