//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class refinanceApplicationLog
    {
        public decimal pk { get; set; }
        public Nullable<decimal> refinance_pk { get; set; }
        public string request_amt { get; set; }
        public string require_redem { get; set; }
        public string require_redem_item { get; set; }
        public string net_amt { get; set; }
        public string os_item { get; set; }
        public string os_item_amt { get; set; }
        public string remarks_refinance { get; set; }
        public string last_upd_user { get; set; }
        public Nullable<System.DateTime> log_date { get; set; }
    }
}
