//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_GetLoanApplicationSearchResult_TaskList
    {
        public string 估價單編號 { get; set; }
        public string 估價單地區 { get; set; }
        public int status_id { get; set; }
        public string 進度 { get; set; }
        public Nullable<bool> 已過期 { get; set; }
        public string 申請日期 { get; set; }
        public string 申請人 { get; set; }
        public string 聯絡電話 { get; set; }
        public string 地址1 { get; set; }
        public string 申請意欲 { get; set; }
        public string 登記人 { get; set; }
        public string 最後覆客日期 { get; set; }
        public string 曾經批核 { get; set; }
        public Nullable<bool> 緊急 { get; set; }
        public Nullable<System.DateTime> replyCus_date { get; set; }
        public string checker1 { get; set; }
        public string checker2 { get; set; }
        public Nullable<bool> is_from_callcenter { get; set; }
        public string callcenter_user_id { get; set; }
        public string user_id { get; set; }
        public Nullable<System.DateTime> last_upd_date { get; set; }
        public string all_status_id { get; set; }
        public Nullable<bool> agent { get; set; }
    }
}
